apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: cowguest
        tier: frontend
    spec:
      containers:
      - name: cowguest
        image: cedretaber/cowguest:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: REDIS_HOST
          value: redis-master
        ports:
        - containerPort: 4000