apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: cowguest
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: cowguest
    tier: frontend